binary_build_commands: '"go mod vendor && make containerized-build"'
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.15-openshift-4.6
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
test_binary_build_commands: '"go mod vendor && make containerized-test"'
tests:
- artifact_dir: /tmp/artifacts
  as: containerized-test
  commands: '"CONTAINER_CMD=docker make containerized-test"'
  container:
    from: src
zz_generated_metadata:
  branch: release-4.7
  org: openshift
  repo: ceph-csi
